### ISSUE TITLE
Poker Interface

### ISSUE THREAD

**Issue by rayhogan** [rayhogan/planningpoker#3]
Create basic UI for displaying Fibonacci sequence buttons and setting story title.

**Comment by simonhoyos** [comment]
@rayhogan any idea on how it should look?

**Comment by rayhogan** [comment]
Hi @simonhoyos I actually have this issue done more or less (first draft anyway), will be doing the PR shortly. It's a very simple app (vanilla JS/css), and an excuse for me to play around with socket.io a bit more really. They'll be a couple of more issues coming on the board in the next few days. I'll consider the app done once a user can create a session, share a link and have people join it to cast story points. If you're interested, keep checking back!

**Comment by simonhoyos** [comment]
@rayhogan Good to know, I'll be checking back if you need any assistance and to check the results :)
